[features]
seeds = false
skip-lint = false
[programs.localnet]
todo_solana = "whziJcQhKnJs9r8ZXM9Um39mbPsaRUamxGq4SXy4EcV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/tien/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
